# -*- coding: utf-8 -*-
"""visionProject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AQ2BSSKp45K0K7xL9S1h4m0XKsT0f3z7

# data preprocessing:
"""

import zipfile
import os

# Extract the zip file
with zipfile.ZipFile('isolated_words_per_user.zip', 'r') as zip_ref:
    zip_ref.extractall("isolated_words_per_user")

import pandas as pd
#import cv2
from PIL import Image
from PIL import ImageFile
ImageFile.LOAD_TRUNCATED_IMAGES = True
Image.LOAD_TRUNCATED_IMAGES = True


main_list = []

main_folder = "/content/isolated_words_per_user/isolated_words_per_user"

counter = 0;

# Iterate through each subfolder
for subfolder_name in os.listdir(main_folder):
    subfolder_path = os.path.join(main_folder, subfolder_name)

    # Check if it is a directory
    if os.path.isdir(subfolder_path):
        counter += 1

        # Iterate through files in the subfolder
        for file_name in os.listdir(subfolder_path):
            file_path = os.path.join(subfolder_path, file_name)

            #only take images of the word abjadiyah
            tokens = file_name.split("_")
            if(tokens[1] != 'abjadiyah'):
              continue

            temp_dic = {'user': tokens[0],
                        'class': tokens[1],
                        'img': Image.open(file_path) }

            main_list.append(temp_dic)

print(main_list[0:3])

df = pd.DataFrame.from_records(main_list)
print(df.info())

print(df.head())

print(df['img'][93].width)
print(df['img'][93].height)

df['user'] = df['user'].str.extract('(\d+)').astype(int)

df['user'] = df['user'].astype('int64')

print(df['user'].head())

print(df['user'].max())
print(df['user'].min())

df['user'] = df['user'] - 1

df.info()

import matplotlib.pyplot as plt

counter = 0

for index, row in df.iterrows():
    plt.imshow(row['img'], cmap='gray')
    plt.title(row['user'])
    plt.axis('off')
    plt.show()
    # img = row['img']
    # img.show()

    counter += 1
    if(counter >= 10):
      break

"""# prepare the data loaders:"""

import torch
from torch.utils.data import Dataset
from torchvision import transforms
from sklearn.preprocessing import LabelEncoder

class ImageDataset(Dataset):
    def __init__(self, dataframe, transform=None):
        self.dataframe = dataframe
        self.transform = transform
        # self.label_encoder = label_encoder

    def __len__(self):
        return len(self.dataframe)

    def __getitem__(self, idx):
        label = self.dataframe.iloc[idx]['user']
        image = self.dataframe.iloc[idx]['img']

        label = torch.tensor(label, dtype=torch.long)

        if self.transform:
            image = self.transform(image)

        return image, label

transform = transforms.Compose([
    transforms.Resize((128, 128)),
    transforms.ToTensor(),
    transforms.Normalize((0.5,), (0.5,))
])

from sklearn.model_selection import train_test_split

train_df, test_df = train_test_split(df, test_size=0.2, random_state=42)

from torch.utils.data import DataLoader


train_dataset = ImageDataset(train_df, transform=transform)
test_dataset = ImageDataset(test_df, transform=transform)

batch_size = 20
train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True, num_workers=2)
test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False, num_workers=2)

"""# CNN models:"""

device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
print(device)

import torch
import torch.nn as nn
import torch.nn.functional as F

class NetCNN(nn.Module):
    def __init__(self):
        super().__init__()
        # Input: 128x128x1
        self.conv1 = nn.Conv2d(1, 6, kernel_size=5)  # Output: 124x124x6
        self.pool = nn.MaxPool2d(kernel_size=2, stride=2)  # Output: 62x62x6
        self.conv2 = nn.Conv2d(6, 16, kernel_size=5)  # Output: 58x58x16
        self.pool2 = nn.MaxPool2d(kernel_size=2, stride=2)  # Output: 29x29x16

        # Flattened size: 29 * 29 * 16 = 13456
        self.fc1 = nn.Linear(29 * 29 * 16, 1200)
        self.fc2 = nn.Linear(1200, 256)
        self.fc3 = nn.Linear(256, 82)  # 82 classes

    def forward(self, x):
        x = self.pool(F.relu(self.conv1(x)))
        x = self.pool2(F.relu(self.conv2(x)))
        x = torch.flatten(x, 1)  # Flatten all dimensions except batch
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x

# Move the model to the appropriate device (e.g., GPU)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
net = NetCNN().to(device)

import torch.optim as optim
criterion = nn.CrossEntropyLoss()
optimizer = optim.SGD(net.parameters(), lr=0.1)

import matplotlib.pyplot as plt

# Initialize lists to store loss and accuracy
epoch_losses = []
epoch_accuracies = []

for epoch in range(20):
    net.train()
    running_loss = 0.0
    i = 0
    correct = 0
    total = 0

    for inputs, labels in train_loader:
        inputs, labels = inputs.to(device), labels.to(device)

        optimizer.zero_grad()
        outputs = net(inputs)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()

        running_loss += loss.item()

        # Calculate accuracy
        _, predicted = outputs.max(1)
        total += labels.size(0)
        correct += predicted.eq(labels).sum().item()

        i += 1
        if i % 20 == 19:
            print(f'[{epoch + 1}, {i + 1:5d}] loss: {running_loss / 100:.3f}')
            running_loss = 0.0

    # Calculate and store epoch loss and accuracy
    epoch_loss = running_loss / len(train_loader)
    epoch_losses.append(epoch_loss)

    epoch_accuracy = 100.0 * correct / total
    epoch_accuracies.append(epoch_accuracy)

    print(f'Epoch {epoch + 1} completed. Loss: {epoch_loss:.3f}, Accuracy: {epoch_accuracy:.2f}%')

print('Finished Training')

# Plot Loss vs. Epoch
plt.figure(figsize=(12, 6))
plt.subplot(1, 2, 1)
plt.plot(range(1, 21), epoch_losses, marker='o', label='Loss')
plt.title('Loss vs. Epoch')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()

# Plot Accuracy vs. Epoch
plt.subplot(1, 2, 2)
plt.plot(range(1, 21), epoch_accuracies, marker='o', label='Accuracy', color='orange')
plt.title('Accuracy vs. Epoch')
plt.xlabel('Epoch')
plt.ylabel('Accuracy (%)')
plt.legend()

plt.tight_layout()
plt.show()

correct = 0
total = 0

net.eval()
with torch.no_grad():
  for data in test_loader:
    images, labels = data
    images, labels = images.to(device), labels.to(device)
    # calculate outputs by running images through the network
    outputs = net(images)
    # the class with the highest energy is what we choose as prediction
    _, predicted = torch.max(outputs.data, 1)
    print(f"predicted: {predicted}")
    print(f"labels: {labels}")

    print("***************************")
    total += labels.size(0)
    correct += (predicted == labels).sum().item()
print(f"correctly predicted: {correct}")
print(f"total: {total}")
print(f'Accuracy of the network on the 10000 test images: {100 * correct// total} %')

"""# task 2: data augmentation:"""

from PIL import Image
import random

percentages = [0.0, 0.05, 0.10, 0.15, 0.20, 0.25, 0.30]

# Crop some images:
def crop_image(image):
    if not isinstance(image, Image.Image):
        raise ValueError("Input must be a Pillow Image object.")

    width, height = image.size

    random_percent = random.choice(percentages)

    start_height = int(height * random_percent)
    end_height = int(height * (1 - random_percent))

    start_width = int(width * random_percent)
    end_width = int(width * (1 - random_percent))

    cropped_img = image.crop((start_width, start_height, end_width, end_height))
    return cropped_img

img = df['img'][20]
# img = cv.cvtColor(img, cv.COLOR_BGR2RGB)

print(img.size)
plt.imshow(img, cmap='gray')
plt.title("original")
plt.axis('off')
plt.show()

cropped = crop_image(img)
plt.imshow(cropped, cmap='gray')
plt.title("blurred")
plt.axis('off')
plt.show()

sampled_df = df.sample(frac=0.3, random_state=42)
new_rows = []

for i, row in sampled_df.iterrows():
    user, label, img = row['user'], row['class'], row['img']
    cropped_img = crop_image(img)

    new_rows.append({'user': user, 'class': label, 'img': cropped_img})

augmented_df = pd.DataFrame(new_rows)
final_df = pd.concat([df, augmented_df], ignore_index=True)

print(final_df.info())

from PIL import Image
import numpy as np

# Add Gaussian noise
def add_gaussian_noise(image, var, mean=20):
    if not isinstance(image, Image.Image):
        raise ValueError("Input must be a Pillow Image object.")

    image_array = np.array(image, dtype=np.float32)

    sigma = var**0.5
    gaussian_noise = np.random.normal(mean, sigma, image_array.shape)

    noisy_image_array = image_array + gaussian_noise

    # Clip values to ensure they stay in valid range
    noisy_image_array = np.clip(noisy_image_array, 0, 255).astype(np.uint8)

    noisy_image = Image.fromarray(noisy_image_array)

    return noisy_image

img = df['img'][20]
# img = cv.cvtColor(img, cv.COLOR_BGR2RGB)

print(img.size)
plt.imshow(img, cmap='gray')
plt.title("original")
plt.axis('off')
plt.show()

blurred = add_gaussian_noise(img, var=1500, mean=20)
plt.imshow(blurred, cmap='gray')
plt.title("blurred")
plt.axis('off')
plt.show()

sampled_df = df.sample(frac=0.3, random_state=42)
new_rows = []

for i, row in sampled_df.iterrows():
    user, label, img = row['user'], row['class'], row['img']
    blurred = add_gaussian_noise(img, var=1500, mean=20)

    new_rows.append({'user': user, 'class': label, 'img': cropped_img})

augmented_df = pd.DataFrame(new_rows)
final_df = pd.concat([final_df, augmented_df], ignore_index=True)

print(final_df.info())

from PIL import Image
import random

# Rotate image by a random angle
def rotate_image(image):
    if not isinstance(image, Image.Image):
        raise ValueError("Input must be a Pillow Image object.")

    degree = random.randint(-30, 30)

    rotated_image = image.rotate(degree, resample=Image.BICUBIC, expand=True)

    return rotated_image

img = df['img'][130]

print(img.size)
plt.imshow(img, cmap='gray')
plt.title("original")
plt.axis('off')
plt.show()

rotated = rotate_image(img)
plt.imshow(rotated, cmap='gray')
plt.title('Rotated Image')
plt.show()

sampled_df = df.sample(frac=0.4, random_state=42)
new_rows = []

for i, row in sampled_df.iterrows():
    user, label, img = row['user'], row['class'], row['img']
    blurred = rotate_image(img)

    new_rows.append({'user': user, 'class': label, 'img': cropped_img})

augmented_df = pd.DataFrame(new_rows)
final_df = pd.concat([final_df, augmented_df], ignore_index=True)

print(final_df.info())

from torch.utils.data import DataLoader
from sklearn.model_selection import train_test_split

train_df, test_df = train_test_split(final_df, test_size=0.2, random_state=42)

train_dataset_aug = ImageDataset(train_df, transform=transform)
test_dataset_aug = ImageDataset(test_df, transform=transform)

batch_size = 20
train_loader_aug = DataLoader(train_dataset_aug, batch_size=batch_size, shuffle=True, num_workers=2)
test_loader_aug = DataLoader(test_dataset_aug, batch_size=batch_size, shuffle=False, num_workers=2)

import torch
import torch.nn as nn
import torch.nn.functional as F

class NetCNN(nn.Module):
    def __init__(self):
        super().__init__()
        # Input: 128x128x1
        self.conv1 = nn.Conv2d(1, 6, kernel_size=5)  # Output: 124x124x6
        self.pool = nn.MaxPool2d(kernel_size=2, stride=2)  # Output: 62x62x6
        self.conv2 = nn.Conv2d(6, 16, kernel_size=5)  # Output: 58x58x16
        self.pool2 = nn.MaxPool2d(kernel_size=2, stride=2)  # Output: 29x29x16

        # Flattened size: 29 * 29 * 16 = 13456
        self.fc1 = nn.Linear(29 * 29 * 16, 1200)
        self.fc2 = nn.Linear(1200, 256)
        self.fc3 = nn.Linear(256, 82)  # 82 classes

    def forward(self, x):
        x = self.pool(F.relu(self.conv1(x)))
        x = self.pool2(F.relu(self.conv2(x)))
        x = torch.flatten(x, 1)  # Flatten all dimensions except batch
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x

# Move the model to the appropriate device (e.g., GPU)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
net = NetCNN().to(device)

import torch.optim as optim
criterion = nn.CrossEntropyLoss()
optimizer = optim.SGD(net.parameters(), lr=0.08)

import matplotlib.pyplot as plt

# Initialize lists to store loss and accuracy
epoch_losses = []
epoch_accuracies = []

for epoch in range(20):
    net.train()
    running_loss = 0.0
    i = 0
    correct = 0
    total = 0

    for inputs, labels in train_loader:
        inputs, labels = inputs.to(device), labels.to(device)

        optimizer.zero_grad()
        outputs = net(inputs)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()

        running_loss += loss.item()

        # Calculate accuracy
        _, predicted = outputs.max(1)
        total += labels.size(0)
        correct += predicted.eq(labels).sum().item()

        i += 1
        if i % 40 == 39:
            print(f'[{epoch + 1}, {i + 1:5d}] loss: {running_loss / 100:.3f}')
            running_loss = 0.0

    # Calculate and store epoch loss and accuracy
    epoch_loss = running_loss / len(train_loader)
    epoch_losses.append(epoch_loss)

    epoch_accuracy = 100.0 * correct / total
    epoch_accuracies.append(epoch_accuracy)

    print(f'Epoch {epoch + 1} completed. Loss: {epoch_loss:.3f}, Accuracy: {epoch_accuracy:.2f}%')

print('Finished Training')

# Plot Loss vs. Epoch
plt.figure(figsize=(12, 6))
plt.subplot(1, 2, 1)
plt.plot(range(1, 21), epoch_losses, marker='o', label='Loss')
plt.title('Loss vs. Epoch')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()

# Plot Accuracy vs. Epoch
plt.subplot(1, 2, 2)
plt.plot(range(1, 21), epoch_accuracies, marker='o', label='Accuracy', color='orange')
plt.title('Accuracy vs. Epoch')
plt.xlabel('Epoch')
plt.ylabel('Accuracy (%)')
plt.legend()

plt.tight_layout()
plt.show()

correct = 0
total = 0

net.eval()
with torch.no_grad():
  for data in test_loader:
    images, labels = data
    images, labels = images.to(device), labels.to(device)
    # calculate outputs by running images through the network
    outputs = net(images)
    # the class with the highest energy is what we choose as prediction
    _, predicted = torch.max(outputs.data, 1)
    print(f"predicted: {predicted}")
    print(f"labels: {labels}")

    print("***************************")
    total += labels.size(0)
    correct += (predicted == labels).sum().item()
print(f"correctly predicted: {correct}")
print(f"total: {total}")
print(f'Accuracy of the network on the 10000 test images: {100 * correct// total} %')

"""# task 4: pretrained CNN model

## ResNet-18:
"""

device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
print(device)

import torch.nn as nn
from torchvision import models

net = models.resnet18(weights='IMAGENET1K_V1')

# Modify the fully connected (fc) layer for 10 classes
num_features = net.fc.in_features
net.fc = nn.Linear(num_features, 82)

net = net.to(device)

import torch
import torchvision
import torchvision.transforms as transforms

transform2 = transforms.Compose(
            [transforms.Resize(256),
            transforms.CenterCrop(224),
            transforms.Grayscale(num_output_channels=3),
            transforms.ToTensor(),
            transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])])

from torch.utils.data import DataLoader


train_dataset = ImageDataset(train_df, transform=transform2)
test_dataset = ImageDataset(test_df, transform=transform2)

batch_size = 20
train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True, num_workers=2)
test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False, num_workers=2)

import torch.optim as optim
criterion = nn.CrossEntropyLoss()
optimizer = optim.SGD(net.parameters(), lr=0.001, momentum=0.9)

import matplotlib.pyplot as plt

# Initialize lists to store loss and accuracy
epoch_losses = []
epoch_accuracies = []

for epoch in range(20):
    net.train()
    running_loss = 0.0
    i = 0
    correct = 0
    total = 0

    for inputs, labels in train_loader:
        inputs, labels = inputs.to(device), labels.to(device)

        optimizer.zero_grad()
        outputs = net(inputs)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()

        running_loss += loss.item()

        # Calculate accuracy
        _, predicted = outputs.max(1)
        total += labels.size(0)
        correct += predicted.eq(labels).sum().item()

        i += 1
        if i % 40 == 39:
            print(f'[{epoch + 1}, {i + 1:5d}] loss: {running_loss / 100:.3f}')
            running_loss = 0.0

    # Calculate and store epoch loss and accuracy
    epoch_loss = running_loss / len(train_loader)
    epoch_losses.append(epoch_loss)

    epoch_accuracy = 100.0 * correct / total
    epoch_accuracies.append(epoch_accuracy)

    print(f'Epoch {epoch + 1} completed. Loss: {epoch_loss:.3f}, Accuracy: {epoch_accuracy:.2f}%')

print('Finished Training')

# Plot Loss vs. Epoch
plt.figure(figsize=(12, 6))
plt.subplot(1, 2, 1)
plt.plot(range(1, 21), epoch_losses, marker='o', label='Loss')
plt.title('Loss vs. Epoch')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()

# Plot Accuracy vs. Epoch
plt.subplot(1, 2, 2)
plt.plot(range(1, 21), epoch_accuracies, marker='o', label='Accuracy', color='orange')
plt.title('Accuracy vs. Epoch')
plt.xlabel('Epoch')
plt.ylabel('Accuracy (%)')
plt.legend()

plt.tight_layout()
plt.show()

correct = 0
total = 0

net.eval()
with torch.no_grad():
  for data in test_loader:
    images, labels = data
    images, labels = images.to(device), labels.to(device)
    # calculate outputs by running images through the network
    outputs = net(images)
    # the class with the highest energy is what we choose as prediction
    _, predicted = torch.max(outputs.data, 1)
    print(f"predicted: {predicted}")
    print(f"labels: {labels}")

    print("***************************")
    total += labels.size(0)
    correct += (predicted == labels).sum().item()
print(f"correctly predicted: {correct}")
print(f"total: {total}")
print(f'Accuracy of the network on the 10000 test images: {100 * correct// total} %')

"""## ResNet-50"""

import torch.nn as nn
from torchvision import models

net = models.resnet50(weights='IMAGENET1K_V1')

# Modify the fully connected (fc) layer for 10 classes
num_features = net.fc.in_features
net.fc = nn.Linear(num_features, 82)

net = net.to(device)

import torch
import torchvision
import torchvision.transforms as transforms

transform2 = transforms.Compose(
            [transforms.Resize(256),
            transforms.CenterCrop(224),
            transforms.Grayscale(num_output_channels=3),
            transforms.ToTensor(),
            transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])])

from torch.utils.data import DataLoader

train_dataset = ImageDataset(train_df, transform=transform2)
test_dataset = ImageDataset(test_df, transform=transform2)

batch_size = 20
train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True, num_workers=2)
test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False, num_workers=2)

import torch.optim as optim
criterion = nn.CrossEntropyLoss()
optimizer = optim.SGD(net.parameters(), lr=0.001, momentum=0.9)

import matplotlib.pyplot as plt

# Initialize lists to store loss and accuracy
epoch_losses = []
epoch_accuracies = []

for epoch in range(20):
    net.train()
    running_loss = 0.0
    i = 0
    correct = 0
    total = 0

    for inputs, labels in train_loader:
        inputs, labels = inputs.to(device), labels.to(device)

        optimizer.zero_grad()
        outputs = net(inputs)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()

        running_loss += loss.item()

        # Calculate accuracy
        _, predicted = outputs.max(1)
        total += labels.size(0)
        correct += predicted.eq(labels).sum().item()

        i += 1
        if i % 40 == 39:
            print(f'[{epoch + 1}, {i + 1:5d}] loss: {running_loss / 100:.3f}')
            running_loss = 0.0

    # Calculate and store epoch loss and accuracy
    epoch_loss = running_loss / len(train_loader)
    epoch_losses.append(epoch_loss)

    epoch_accuracy = 100.0 * correct / total
    epoch_accuracies.append(epoch_accuracy)

    print(f'Epoch {epoch + 1} completed. Loss: {epoch_loss:.3f}, Accuracy: {epoch_accuracy:.2f}%')

print('Finished Training')

# Plot Loss vs. Epoch
plt.figure(figsize=(12, 6))
plt.subplot(1, 2, 1)
plt.plot(range(1, 21), epoch_losses, marker='o', label='Loss')
plt.title('Loss vs. Epoch')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()

# Plot Accuracy vs. Epoch
plt.subplot(1, 2, 2)
plt.plot(range(1, 21), epoch_accuracies, marker='o', label='Accuracy', color='orange')
plt.title('Accuracy vs. Epoch')
plt.xlabel('Epoch')
plt.ylabel('Accuracy (%)')
plt.legend()

plt.tight_layout()
plt.show()

correct = 0
total = 0

net.eval()
with torch.no_grad():
  for data in test_loader:
    images, labels = data
    images, labels = images.to(device), labels.to(device)
    # calculate outputs by running images through the network
    outputs = net(images)
    # the class with the highest energy is what we choose as prediction
    _, predicted = torch.max(outputs.data, 1)
    print(f"predicted: {predicted}")
    print(f"labels: {labels}")

    print("***************************")
    total += labels.size(0)
    correct += (predicted == labels).sum().item()
print(f"correctly predicted: {correct}")
print(f"total: {total}")
print(f'Accuracy of the network on the 10000 test images: {100 * correct// total} %')